# pylint: disable=invalid-name
"""Drop the primary key of the usage table.

Revision ID: 9f4b6184b2f8
Revises: b65796c99771
Create Date: 2024-10-10 11:28:39.846967

"""

from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision = "9f4b6184b2f8"
down_revision = "b65796c99771"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("usage_pkey", "usage", type_="primary", schema="accounting")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("usage_pkey", "usage", ["id"], schema="accounting")
    # ### end Alembic commands ###
