---

version: '3'

services:
  app:
    image: rctab:latest
    container_name: rctab_app
    environment:
      MAX_WORKERS: 1
    env_file:
      - .env
      - .auth.env
    ports:
      - "8000:80"
