---


services:
  database:
    image: docker.io/postgres:14
    container_name: rctab_db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    profiles:
      - serve
      - db_only
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: rctab_app
    environment:
      DB_HOST: rctab_db
      DB_PASSWORD: password
      DB_USER: postgres
      MAX_WORKERS: 1
      DB_PORT: 5432
    env_file:
      - ../.env
      - ../.auth.env
    ports:
      - "8000:80"
    profiles:
      - serve
      - app_only
