---

name: Publish Docker image

on:
  release:
    # Publish on release
    types:
      - published

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check that we can build docker container image
        run: docker build -t rctab:latest .

  push_to_registry:
    needs: docker_build
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: Dockerfile
#          tags: turingrc/rctab
#          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
