name: Deploy API image to Docker Hub

on:
  release:
    types:
      - published

jobs:
  deploy_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Get release tag
        id: current_release
        run: |
          CURRENT_RELEASE=${{ github.event.release.tag_name }}
          echo "CURRENT_RELEASE=${CURRENT_RELEASE}" >> $GITHUB_ENV
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_RELEASE"
          MAJOR_VERSION_NUMBER="${VERSION_PARTS[0]}"
          echo "MAJOR_VERSION_NUMBER=${MAJOR_VERSION_NUMBER}" >> $GITHUB_ENV
          echo "The current release is $CURRENT_RELEASE"
          echo "The current major version number is $MAJOR_VERSION_NUMBER"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push current release and latest tag to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: |
            turingrc/rctab-api:${{ env.CURRENT_RELEASE }}
            turingrc/rctab-api:${{ env.MAJOR_VERSION_NUMBER }}.latest
          push: true
